version: '3.7'

services:

  server:
    build:
      context: .
      args:
        - NODE_VERSION=18.15.0
        - NPM_VERSION=9.5.0
        - NOCACHE=$${NOCACHE}
        - VRCHATS_USER=$USER
      dockerfile: Dockerfile
      target: builder
      ssh:
        - default
    ports:
      - "8443:8443"
      - "2053:2053"

    # mounting the project so we execute the existing state from our local filesystem
    volumes:
      - ".:/var/www/vrchats"
    working_dir: /var/www/vrchats
    env_file: .env
    # watch and rerun on change
    command: "reflex -v -r '\\.js$$' -s -- pm2-runtime /var/www/vrchats/app.config.js"
